version: "3.8"

services:
  wishlistapp_db:
    image: mongo:7.0.4
    container_name: wishlistapp_db
    hostname: wishlistapp_db
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    volumes:
      - ./mongo_data:/data/db
    networks:
      - wishlistapp_network

  wishlistapp_core:
    image: wishlistapp_core
    container_name: wishlistapp_core
    hostname: wishlistapp_core
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - MONGO_HOST=wishlistapp_db
      - MONGO_LOCAL_PORT=$MONGO_PORT
      - MONGO_DATABASE=$MONGO_DATABASE
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    depends_on:
      - wishlistapp_db
    networks:
      - wishlistapp_network


networks:
  wishlistapp_network:
    driver: bridge